apiVersion: v1
kind: Secret
metadata: 
  name: mongodb-secret
type: Opaque #Opaque means the info has hidden and secret 
data: 
  mongo-root-username: cm9vdA==  #use encoded usernamem
  mongo-root-password: cGFzcw== #use encoded password
